# Generated by Django 4.1.4 on 2023-01-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, verbose_name='телефон для связи'),
        ),
    ]
