# Generated by Django 4.1.5 on 2023-05-21 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecn', '0003_alter_incityobject_price_alter_outcityobject_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomsLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms_layout', models.CharField(max_length=55, verbose_name='Планировка')),
            ],
        ),
        migrations.AlterField(
            model_name='incityobject',
            name='rooms_layout',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='ecn.roomslayout', verbose_name='планировка'),
        ),
    ]
