# Generated by Django 4.1.5 on 2023-05-21 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecn', '0004_roomslayout_alter_incityobject_rooms_layout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomslayout',
            options={'ordering': ['id'], 'verbose_name': 'Планировка', 'verbose_name_plural': 'Вид планировки'},
        ),
    ]
