# Generated by Django 4.1.4 on 2023-01-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecn', '0007_bath_contacts_electricity_forestnearly_gallery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcityobject',
            name='land_square',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='в сотках, 2 знака после запятой', max_digits=4, verbose_name='площадь участка'),
        ),
    ]
