# Generated by Django 4.1.4 on 2023-01-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecn', '0009_alter_contacts_image_alter_gallery_gallery_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='gallery_image',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='gallery2',
            name='gallery_image2',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='graphics',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='incityobject',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d', verbose_name='Основное изображение'),
        ),
        migrations.AlterField(
            model_name='incityobjecttype',
            name='icon',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d', verbose_name='иконка(картинка) для типа объекта'),
        ),
        migrations.AlterField(
            model_name='outcityobject',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d', verbose_name='Основное изображение'),
        ),
        migrations.AlterField(
            model_name='outcityobjecttype',
            name='icon',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d', verbose_name='иконка(картинка) для типа объекта'),
        ),
    ]
