# Generated by Django 4.1.5 on 2023-01-20 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecn', '0011_alter_incityobject_estate_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incityobject',
            name='estate_agent',
            field=models.ForeignKey(blank=True, default=1, help_text='специалист по объекту', on_delete=django.db.models.deletion.CASCADE, related_name='realtor', to=settings.AUTH_USER_MODEL, verbose_name='агент по недвижимости'),
        ),
        migrations.AlterField(
            model_name='incityobject',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True, verbose_name='URL'),
        ),
    ]
