# Generated by Django 4.1.4 on 2023-02-06 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecn', '0013_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='galleryLink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecn.incityobject', verbose_name='Ссылка на объект'),
        ),
        migrations.AlterField(
            model_name='gallery2',
            name='galleryLink2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecn.outcityobject', verbose_name='Ссылка на объект'),
        ),
    ]
